// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwOsvUKBIlxIF73v_WOJD64_6SPV61gEk',
    appId: '1:318410227659:web:3a0c26f79e6d15bb20404e',
    messagingSenderId: '318410227659',
    projectId: 'ryden-2',
    authDomain: 'ryden-2.firebaseapp.com',
    databaseURL: 'https://ryden-2-default-rtdb.firebaseio.com',
    storageBucket: 'ryden-2.firebasestorage.app',
    measurementId: 'G-70TX0077YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk1s5IbMw_MqwAptGqVm9Nx8Hi8qlizjg',
    appId: '1:318410227659:android:97f8e5f7e5c2126820404e',
    messagingSenderId: '318410227659',
    projectId: 'ryden-2',
    databaseURL: 'https://ryden-2-default-rtdb.firebaseio.com',
    storageBucket: 'ryden-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJGE10rjqgX90Pj4ohG2sjMnRkWMnpFOo',
    appId: '1:318410227659:ios:65299ecad6a8802520404e',
    messagingSenderId: '318410227659',
    projectId: 'ryden-2',
    databaseURL: 'https://ryden-2-default-rtdb.firebaseio.com',
    storageBucket: 'ryden-2.firebasestorage.app',
    androidClientId: '318410227659-s9i5gc73r1co4ebtb780u7sihslpdktp.apps.googleusercontent.com',
    iosClientId: '318410227659-umqk5et1qbm5c9vofvol052365ngeapo.apps.googleusercontent.com',
    iosBundleId: 'com.ryden.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJGE10rjqgX90Pj4ohG2sjMnRkWMnpFOo',
    appId: '1:318410227659:ios:65299ecad6a8802520404e',
    messagingSenderId: '318410227659',
    projectId: 'ryden-2',
    storageBucket: 'ryden-2.firebasestorage.app',
    iosBundleId: 'com.ryden.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwOsvUKBIlxIF73v_WOJD64_6SPV61gEk',
    appId: '1:318410227659:web:f7cb388c7d8f662820404e',
    messagingSenderId: '318410227659',
    projectId: 'ryden-2',
    authDomain: 'ryden-2.firebaseapp.com',
    databaseURL: 'https://ryden-2-default-rtdb.firebaseio.com',
    storageBucket: 'ryden-2.firebasestorage.app',
    measurementId: 'G-9RH7VT66CP',
  );

}